[package]
name = "flamingo-remarkable"
version = "0.1.0"
authors = ["theoxao <theoxao@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libremarkable = "0.3.2"
